### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by awsp** [awsp/handsontable-meteor#18]
- [ ] Clean up the lib as the package size is getting bigger.
- [ ] Setup and write some automated cucumber tests.
- [x] Update to 0.20.3
- [x] Update to 0.21.0
- [ ] Crash on Meteor 1.3 beta
- [ ] ES6 Syntax

**Comment by stemcc** [comment]
Also looks like Handsontable just released update 20.3

**Comment by awsp** [comment]
Yup, will do it this weekend or so. Had been really busy the theses 2 weeks. I also had been trying the new meteor 1.3 beta, seems like a lot of these client-only packages including this package don't function properly. That might require a rewrite I guess...

**Comment by stemcc** [comment]
That sounds troublesome, this package is integral to my work. What kind of errors is 1.3 giving you? Are they related to new features or things are now just generally broken?

**Comment by awsp** [comment]
Yea, I am using it in couple projects too. 
It generally broke. Meteor simply failed to compile it. 
This sounds like it's a node-side problem, but I am still investigating it. 

``` sh
W20160115-18:42:13.934(0)? (STDERR)           
W20160115-18:42:13.934(0)? (STDERR) /home/ubuntu/.meteor/packages/meteor-tool/.1.1.11-modules.3.1j2gyye++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20160115-18:42:13.935(0)? (STDERR)                                             throw(ex);
W20160115-18:42:13.935(0)? (STDERR)                                                   ^
W20160115-18:42:13.945(0)? (STDERR) TypeError: Property 'default' of object [object Object] is not a function
W20160115-18:42:13.946(0)? (STDERR)     at meteor-13.js:26:17
W20160115-18:42:13.946(0)? (STDERR)     at /home/ubuntu/workspace/.meteor/local/build/programs/server/boot.js:249:5
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.
```
